services:
    folia:
        stdin_open: true
        tty: true
        ports:
            - 25575:25575
            - 25565:25565
            - 24454:24454/udp
        container_name: endkind-folia
        volumes:
            - endkind-folia:/folia
        environment:
            - MAX_RAM=24G
            - MINECRAFT_EULA=true
        restart: always
        image: endkind/folia:latest
volumes:
    endkind-folia:
